protected/models/Alumno.php
<?php

Yii::import('application.models._base.BaseAlumno');

class Alumno extends BaseAlumno
{
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}
}

protected/controllers/AlumnoController.php
<?php

class AlumnoController extends GxController {


	public function actionView($id) {
		$this->render('view', array(
			'model' => $this->loadModel($id, 'Alumno'),
		));
	}
        
        /*public function actionVer($id) {
		$this->render('ver', array(
			'model' => $this->loadModel($id, 'Alumno'),
		));
	}*/

	public function actionCreate() {
		$model = new Alumno;


		if (isset($_POST['Alumno'])) {
			$model->setAttributes($_POST['Alumno']);

			if ($model->save()) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('create', array( 'model' => $model));
	}

	public function actionUpdate($id) {
		$model = $this->loadModel($id, 'Alumno');


		if (isset($_POST['Alumno'])) {
			$model->setAttributes($_POST['Alumno']);

			if ($model->save()) {
				$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('update', array(
				'model' => $model,
				));
	}

	public function actionDelete($id) {
		if (Yii::app()->getRequest()->getIsPostRequest()) {
			$this->loadModel($id, 'Alumno')->delete();

			if (!Yii::app()->getRequest()->getIsAjaxRequest())
				$this->redirect(array('admin'));
		} else
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
	}

	public function actionIndex() {
		$dataProvider = new CActiveDataProvider('Alumno');
		$this->render('index', array(
			'dataProvider' => $dataProvider,
		));
	}

        public function actionVertodos(){ //nombre en url
            $modelo_alumno = new Alumno('search'); //ambiente de búsqueda
            $modelo_alumno->unsetattributes(); //limpiar atributos de busqueda
            //$modelo_alumno->nombre = 'Curso_yii';
            if(isset($_GET['Alumno']))
                $modelo_alumno->attributes=$_GET['Alumno'];
            
            $this->render('ver_todos',array('alumno'=>$modelo_alumno)); //cargar y mostrar vista, por defecto se mete a la carpeta alumno
            //$this->renderPartial();
        }
	public function actionAdmin() {
		$model = new Alumno('search');
		$model->unsetAttributes();

		if (isset($_GET['Alumno']))
			$model->setAttributes($_GET['Alumno']);

		$this->render('admin', array(
			'model' => $model,
		));
	}
        
        public function actionMirar($id){
            $modelo_alumno=$this->loadModel($id, 'Alumno');
            $this->render('ver', array('alumno'=>$modelo_alumno));
        }


        /*public function actionVerTodos() {
		$model = new Alumno('search');
		$model->unsetAttributes();

		if (isset($_GET['Alumno']))
			$model->setAttributes($_GET['Alumno']);

		$this->render('verTodos', array(
			'model' => $model,
		));
	}*/


}

protected/controllers/EscuelaController.php
<?php

class EscuelaController extends GxController {


	public function actionView($id) {
		$this->render('view', array(
			'model' => $this->loadModel($id, 'Escuela'),
		));
	}

	public function actionCreate() {
		$model = new Escuela;

		$this->performAjaxValidation($model, 'escuela-form');

		if (isset($_POST['Escuela'])) {
			$model->setAttributes($_POST['Escuela']);

			if ($model->save()) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('create', array( 'model' => $model));
	}

	public function actionUpdate($id) {
		$model = $this->loadModel($id, 'Escuela');

		$this->performAjaxValidation($model, 'escuela-form');

		if (isset($_POST['Escuela'])) {
			$model->setAttributes($_POST['Escuela']);

			if ($model->save()) {
				$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('update', array(
				'model' => $model,
				));
	}

	public function actionDelete($id) {
		if (Yii::app()->getRequest()->getIsPostRequest()) {
			$this->loadModel($id, 'Escuela')->delete();

			if (!Yii::app()->getRequest()->getIsAjaxRequest())
				$this->redirect(array('admin'));
		} else
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
	}

	public function actionIndex() {
		$dataProvider = new CActiveDataProvider('Escuela');
		$this->render('index', array(
			'dataProvider' => $dataProvider,
		));
	}

	public function actionAdmin() {
		$model = new Escuela('search');
		$model->unsetAttributes();

		if (isset($_GET['Escuela']))
			$model->setAttributes($_GET['Escuela']);

		$this->render('admin', array(
			'model' => $model,
		));
	}

}

protected/views/alumno/_form.php
<div class="form">


<?php $form = $this->beginWidget('GxActiveForm', array(
	'id' => 'alumno-form',
	'enableAjaxValidation' => true,
));
?>

	<p class="note">
		<?php echo Yii::t('app', 'Fields with'); ?> <span class="required">*</span> <?php echo Yii::t('app', 'are required'); ?>.
	</p>

	<?php echo $form->errorSummary($model); ?>

		<div class="row">
		<?php echo $form->labelEx($model,'escuela_id'); ?>
		<?php echo $form->dropDownList($model, 'escuela_id', GxHtml::listDataEx(Escuela::model()->findAllAttributes(null, true))); ?>
		<?php echo $form->error($model,'escuela_id'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'nombre'); ?>
		<?php echo $form->textField($model, 'nombre', array('maxlength' => 45)); ?>
		<?php echo $form->error($model,'nombre'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'sexo'); ?>
		<?php echo $form->textField($model, 'sexo', array('maxlength' => 45)); ?>
		<?php echo $form->error($model,'sexo'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'curso'); ?>
		<?php echo $form->textField($model, 'curso', array('maxlength' => 45)); ?>
		<?php echo $form->error($model,'curso'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'rut'); ?>
		<?php echo $form->textField($model, 'rut'); ?>
		<?php echo $form->error($model,'rut'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'apellido_paterno'); ?>
		<?php echo $form->textField($model, 'apellido_paterno', array('maxlength' => 45)); ?>
		<?php echo $form->error($model,'apellido_paterno'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'apellido_materno'); ?>
		<?php echo $form->textField($model, 'apellido_materno', array('maxlength' => 45)); ?>
		<?php echo $form->error($model,'apellido_materno'); ?>
		</div><!-- row -->


<?php
echo GxHtml::submitButton(Yii::t('app', 'Save'));
$this->endWidget();
?>
</div><!-- form -->

protected/views/alumno/_search.php
<div class="wide form">

<?php $form = $this->beginWidget('GxActiveForm', array(
	'action' => Yii::app()->createUrl($this->route),
	'method' => 'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model, 'id'); ?>
		<?php echo $form->textField($model, 'id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'escuela_id'); ?>
		<?php echo $form->dropDownList($model, 'escuela_id', GxHtml::listDataEx(Escuela::model()->findAllAttributes(null, true)), array('prompt' => Yii::t('app', 'All'))); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'nombre'); ?>
		<?php echo $form->textField($model, 'nombre', array('maxlength' => 45)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'sexo'); ?>
		<?php echo $form->textField($model, 'sexo', array('maxlength' => 45)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'curso'); ?>
		<?php echo $form->textField($model, 'curso', array('maxlength' => 45)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'rut'); ?>
		<?php echo $form->textField($model, 'rut'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'apellido_paterno'); ?>
		<?php echo $form->textField($model, 'apellido_paterno', array('maxlength' => 45)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'apellido_materno'); ?>
		<?php echo $form->textField($model, 'apellido_materno', array('maxlength' => 45)); ?>
	</div>

	<div class="row buttons">
		<?php echo GxHtml::submitButton(Yii::t('app', 'Search')); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/alumno/_view.php
<div class="view">

	<?php echo GxHtml::encode($data->getAttributeLabel('id')); ?>:
	<?php echo GxHtml::link(GxHtml::encode($data->id), array('view', 'id' => $data->id)); ?>
	<br />

	<?php echo GxHtml::encode($data->getAttributeLabel('escuela_id')); ?>:
		<?php echo GxHtml::encode(GxHtml::valueEx($data->escuela)); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('nombre')); ?>:
	<?php echo GxHtml::encode($data->nombre); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('sexo')); ?>:
	<?php echo GxHtml::encode($data->sexo); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('curso')); ?>:
	<?php echo GxHtml::encode($data->curso); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('rut')); ?>:
	<?php echo GxHtml::encode($data->rut); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('apellido_paterno')); ?>:
	<?php echo GxHtml::encode($data->apellido_paterno); ?>
	<br />
	<?php /*
	<?php echo GxHtml::encode($data->getAttributeLabel('apellido_materno')); ?>:
	<?php echo GxHtml::encode($data->apellido_materno); ?>
	<br />
	*/ ?>

</div>

protected/views/alumno/admin.php
<?php

$this->breadcrumbs = array(
	$model->label(2) => array('index'),
	Yii::t('app', 'Manage'),
);

$this->menu = array(
		array('label'=>Yii::t('app', 'List') . ' ' . $model->label(2), 'url'=>array('index')),
		array('label'=>Yii::t('app', 'Create') . ' ' . $model->label(), 'url'=>array('create')),
	);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('alumno-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1><?php echo Yii::t('app', 'Manage') . ' ' . GxHtml::encode($model->label(2)); ?></h1>

<p>
You may optionally enter a comparison operator (&lt;, &lt;=, &gt;, &gt;=, &lt;&gt; or =) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo GxHtml::link(Yii::t('app', 'Advanced Search'), '#', array('class' => 'search-button')); ?>
<div class="search-form">
<?php $this->renderPartial('_search', array(
	'model' => $model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id' => 'alumno-grid',
	'dataProvider' => $model->search(),
	'filter' => $model,
	'columns' => array(
		'id',
		array(
				'name'=>'escuela_id',
				'value'=>'GxHtml::valueEx($data->escuela)',
				'filter'=>GxHtml::listDataEx(Escuela::model()->findAllAttributes(null, true)),
				),
		'nombre',
                'apellido_paterno',
		'apellido_materno',
		'sexo',
		'curso',
		'rut',		
		array(
			'class' => 'CButtonColumn',
		),
	),
)); ?>

protected/views/alumno/create.php
<?php

$this->breadcrumbs = array(
	$model->label(2) => array('index'),
	Yii::t('app', 'Create'),
);

$this->menu = array(
	array('label'=>Yii::t('app', 'List') . ' ' . $model->label(2), 'url' => array('index')),
	array('label'=>Yii::t('app', 'Manage') . ' ' . $model->label(2), 'url' => array('admin')),
);
?>

<h1><?php echo Yii::t('app', 'Create') . ' ' . GxHtml::encode($model->label()); ?></h1>

<?php
$this->renderPartial('_form', array(
		'model' => $model,
		'buttons' => 'create'));
?>

protected/views/alumno/index.php
<?php

$this->breadcrumbs = array(
	Alumno::label(2),
	Yii::t('app', 'Index'),
);

$this->menu = array(
	array('label'=>Yii::t('app', 'Create') . ' ' . Alumno::label(), 'url' => array('create')),
	array('label'=>Yii::t('app', 'Manage') . ' ' . Alumno::label(2), 'url' => array('admin')),
);
?>

<h1><?php echo GxHtml::encode(Alumno::label(2)); ?></h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); 

protected/views/alumno/update.php
<?php

$this->breadcrumbs = array(
	$model->label(2) => array('index'),
	GxHtml::valueEx($model) => array('view', 'id' => GxActiveRecord::extractPkValue($model, true)),
	Yii::t('app', 'Update'),
);

$this->menu = array(
	array('label' => Yii::t('app', 'List') . ' ' . $model->label(2), 'url'=>array('index')),
	array('label' => Yii::t('app', 'Create') . ' ' . $model->label(), 'url'=>array('create')),
	array('label' => Yii::t('app', 'View') . ' ' . $model->label(), 'url'=>array('view', 'id' => GxActiveRecord::extractPkValue($model, true))),
	array('label' => Yii::t('app', 'Manage') . ' ' . $model->label(2), 'url'=>array('admin')),
);
?>

<h1><?php echo Yii::t('app', 'Update') . ' ' . GxHtml::encode($model->label()) . ' ' . GxHtml::encode(GxHtml::valueEx($model)); ?></h1>

<?php
$this->renderPartial('_form', array(
		'model' => $model));
?>

protected/views/alumno/ver.php
<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

$this->widget('bootstrap.widgets.TbDetailView', array(
	'data' => $alumno,
        'type' => 'bordered striped condensed',
        
	'attributes' => array(
//'id',
/*array(
			'name' => 'escuela',
			'type' => 'raw',
			'value' => $model->escuela !== null ? GxHtml::link(GxHtml::encode(GxHtml::valueEx($model->escuela)), array('escuela/view', 'id' => GxActiveRecord::extractPkValue($model->escuela, true))) : null,
			),*/
        'nombre',
        'apellido_paterno',
        'apellido_materno',
        'sexo',
        'curso',
        'rut',
            ),
     ));
?>

protected/views/alumno/verTodos.php
<?php

$this->breadcrumbs = array(
	$model->label(2) => array('index'),
	Yii::t('app', 'Manage'),
);

$this->menu = array(
		array('label'=>Yii::t('app', 'List') . ' ' . $model->label(2), 'url'=>array('index')),
		//array('label'=>Yii::t('app', 'Create') . ' ' . $model->label(), 'url'=>array('create')),
	);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('alumno-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1><?php echo Yii::t('app', 'Manage') . ' ' . GxHtml::encode($model->label(2)); ?></h1>

<p>
You may optionally enter a comparison operator (&lt;, &lt;=, &gt;, &gt;=, &lt;&gt; or =) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo GxHtml::link(Yii::t('app', 'Advanced Search'), '#', array('class' => 'search-button')); ?>
<div class="search-form">
<?php $this->renderPartial('_search', array(
	'model' => $model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id' => 'alumno-grid',
	'dataProvider' => $model->search(),
	'filter' => $model,
	'columns' => array(
		'id',
		array(
				'name'=>'escuela_id',
				'value'=>'GxHtml::valueEx($data->escuela)',
				'filter'=>GxHtml::listDataEx(Escuela::model()->findAllAttributes(null, true)),
				),
		'nombre',
		'sexo',
		'curso',
		'rut',
		'apellido_paterno',
		'apellido_materno',
		array(
			'class' => 'CButtonColumn',
		),
	),
)); ?>

protected/views/alumno/ver_todos.php
<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
?>

<?php /*$this->widget('zii.widgets.grid.CGridView', array(
	'id' => 'tabla-alumno',
	'dataProvider' => $alumno->search(),
	'filter' => $alumno,
	'columns' => array(
                
		//'id',
		/*array(
				'name'=>'escuela_id',
				'value'=>'GxHtml::valueEx($data->escuela)',
				'filter'=>GxHtml::listDataEx(Escuela::model()->findAllAttributes(null, true)),
				),
		//'nombre',
                array('name'=>'nombre',filter=>false), //no filtrar por nombre
                'rut',
		//'sexo',
		//'curso',
		'apellido_paterno',
		'apellido_materno',
		/*array(
			'class' => 'CButtonColumn',
		),
	),
)); */?>

<?php $this->widget('bootstrap.widgets.TbGridView',array(
'id'=>'tabla-alumno', //id tabla
'dataProvider'=>$alumno->search(), //proveedor de datos
'filter'=>$alumno, //filto
'type'=>'striped',//css tabla
'template'=>'{pager}{items}{summary}', //despliege de items
'columns'=>array(
//'id',
array('name'=>'nombre'),
    'apellido_paterno',
    'apellido_materno',
'rut',
'sexo',
'curso',
//'direccion',
//'ciudad',
array(
'class'=>'bootstrap.widgets.TbButtonColumn',
'template' => '{ver} {update} {borrar}',
'buttons' => array(
'ver' => array(
'label'=> 'Ver',
    'url'=>'Yii::app()->createUrl("alumno/mirar", array("id"=>$data->id))',
'options'=>array(
'class'=>'btn-info btn-small view'
)
), 
'update' => array(
'label'=> 'Actualizar',
'options'=>array(
'class'=>'btn-warning btn-small update'
)
),
'borrar' => array(
'label'=> 'Eliminar',
    'icon'=> 'trash', //editar icono
'options'=>array(
'class'=>'btn-danger btn-small delete'
)
)
),
'htmlOptions'=>array('style'=>'width: 115px'),
)
),
)); ?>

protected/views/alumno/view.php
<?php

$this->breadcrumbs = array(
	$model->label(2) => array('index'),
	GxHtml::valueEx($model),
);

$this->menu=array(
	array('label'=>Yii::t('app', 'List') . ' ' . $model->label(2), 'url'=>array('index')),
	array('label'=>Yii::t('app', 'Create') . ' ' . $model->label(), 'url'=>array('create')),
	array('label'=>Yii::t('app', 'Update') . ' ' . $model->label(), 'url'=>array('update', 'id' => $model->id)),
	array('label'=>Yii::t('app', 'Delete') . ' ' . $model->label(), 'url'=>'#', 'linkOptions' => array('submit' => array('delete', 'id' => $model->id), 'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>Yii::t('app', 'Manage') . ' ' . $model->label(2), 'url'=>array('admin')),
);
?>

<h1><?php echo Yii::t('app', 'View') . ' ' . GxHtml::encode($model->label()) . ' ' . GxHtml::encode(GxHtml::valueEx($model)); ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data' => $model,
	'attributes' => array(
'id',
array(
			'name' => 'escuela',
			'type' => 'raw',
			'value' => $model->escuela !== null ? GxHtml::link(GxHtml::encode(GxHtml::valueEx($model->escuela)), array('escuela/view', 'id' => GxActiveRecord::extractPkValue($model->escuela, true))) : null,
			),
'nombre',
'sexo',
'curso',
'rut',
'apellido_paterno',
'apellido_materno',
	),
)); ?>